name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GHDL
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: mcode
      - name: Test
        run: |
          pushd vivado/vhdl
          make init
          make run
          popd
